spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elasticsearch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    # DB username
    username: root
    # DB password
    password: 1q2w3e4r